micronaut:
  application:
    name: mnFunding
datasources:
  default:
    url: jdbc:mysql://localhost:3306/mn_funding
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'illusion'
    schema-generate: NONE
    dialect: MYSQL
liquibase:
  datasources:
    default:
      enabled: true
      change-log: 'classpath:db/liquibase-changelog.xml'
      drop-first: false
